spin_version = "1"
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
description = ""
name = "fulfilmentprocessor"
# Ip address is statically configured in redis service yaml
trigger = { type = "mqtt", address = "mqtt://10.43.236.145:1883", qos = 0 }
version = "0.1.0"

[[component]]
id = "fulfilmentprocessor"
source = "target/wasm32-wasi/release/fulfilmentprocessor_mqtt.wasm"
environment = { REDIS_ADDRESS = "redis://10.43.236.144:6379" }
allowed_http_hosts = []
[component.trigger]
topic="neworders"
[component.build]
command = "cargo build --target wasm32-wasi --release"
