---
apiVersion: v1
kind: Service
metadata:
  name: redis-stack
spec:
  type: NodePort
  # This cluster ip is static, used by other pods within the cluster, if you change it here change it in other places too.
  # Change this to service's dns name later.
  clusterIP: 10.43.236.144
  ports:
    - name: redis-stack-server
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30002
    - name: redis-stack
      protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30010
  selector:
    app: redis-stack