spin_version = "1"
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
description = ""
name = "fulfilmentprocessor"
# Ip address is statically configured in redis service yaml
trigger = { type = "redis", address = "redis://10.43.236.144:6379" }
version = "0.1.0"

[[component]]
id = "fulfilmentprocessor"
source = "target/wasm32-wasi/release/fulfilmentprocessor.wasm"
environment = { REDIS_ADDRESS = "redis://10.43.236.144:6379" }
allowed_http_hosts = []
[component.trigger]
channel = "neworders"
[component.build]
command = "cargo build --target wasm32-wasi --release"
