spin_manifest_version = "1"
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
description = ""
name = "eventprocessor"
trigger = { type = "redis", address = "redis://localhost:6379" }
version = "0.1.0"

[[component]]
id = "eventprocessor"
source = "target/wasm32-wasi/release/eventprocessor.wasm"
allowed_http_hosts = []
[component.trigger]
channel = "orders"
[component.build]
command = "cargo build --target wasm32-wasi --release"
