spin_version = "1"
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
description = ""
name = "eventprocessor"
# Ip address is statically configured in redis service yaml
trigger = { type = "redis", address = "redis://10.43.236.144:6379" }
version = "0.1.0"

[[component]]
id = "eventprocessor"
source = "target/wasm32-wasi/release/eventprocessor.wasm"
allowed_http_hosts = []
[component.trigger]
channel = "telemetry"
[component.build]
command = "cargo build --target wasm32-wasi --release"
