spin_manifest_version = "1"
authors = ["Suneet Nangia <suneetnangia@gmail.com>"]
description = ""
name = "eventprocessor"
# 172.17.0.1 is the default docker interface IP address
trigger = { type = "redis", address = "redis://172.17.0.1:6379" }
version = "0.1.0"

[[component]]
id = "eventprocessor"
source = "target/wasm32-wasi/release/eventprocessor.wasm"
allowed_http_hosts = []
[component.trigger]
channel = "telemetry"
[component.build]
command = "cargo build --target wasm32-wasi --release"
